name: '🚀 Plugin Release Deploy Action'
description: 'Release and deploy WordPress plugins using PHP and Node.'
inputs:
  php-version:
    description: 'PHP version to setup'
    required: true
    default: '7.4'
  node-version:
    description: 'Node version to setup'
    required: true
    default: '16'
  plugin-slug:
    description: 'Slug for the WordPress plugin'
    required: true
  build-dir:
    description: 'Build directory for the WordPress plugin'
    required: true
  zip-file:
    description: 'Zip file to upload to release'
    required: true
  dry-run:
    description: 'Flag to perform a dry run of the deployment'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Run release-please
      uses: google-github-actions/release-please-action@v3
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        command: manifest
        default-branch: main

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      if: ${{ steps.release.outputs.releases_created }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: pcov

    - name: Install PHP dependencies
      if: ${{ steps.release.outputs.releases_created }}
      uses: ramsey/composer-install@v1
      with:
        composer-options: '-oa --no-dev'

    - name: Install and Setup Node
      if: ${{ steps.release.outputs.releases_created }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install NPM dependencies
      if: ${{ steps.release.outputs.releases_created }}
      run: |
        npm install

    - name: Build The Artifact
      if: ${{ steps.release.outputs.releases_created }}
      run: |
        npm run build

    - name: Upload zip to release
      if: ${{ steps.release.outputs.releases_created }}
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ${{ inputs.zip-file }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ steps.release.outputs.tag_name }}

    - name: 🚀 Deploy WordPress Plugin
      if: ${{ steps.release.outputs.releases_created }}
      uses: 10up/action-wordpress-plugin-deploy@develop
      env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ inputs.plugin-slug }}
          BUILD_DIR: ${{ inputs.build-dir }}
          INPUT_DRY_RUN: ${{ inputs.dry-run }}
          VERSION: ${{ steps.release.outputs.tag_name }}
