name: '🚀 Plugin Release Deploy Action'
description: 'Release and deploy WordPress plugins using PHP and Node.'

inputs:
  php-version:
    description: 'PHP version to setup'
    required: true
    default: '7.4'
  node-version:
    description: 'Node version to setup'
    required: false
    default: ''
  plugin-slug:
    description: 'Slug for the WordPress plugin'
    required: true
  build-dir:
    description: 'Build directory for the WordPress plugin'
    required: true
  zip-file:
    description: 'Zip file to upload to release'
    required: true
  svn-username:
    description: 'SVN username for WordPress plugin deployment'
    required: true
  svn-password:
    description: 'SVN password for WordPress plugin deployment'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true
  dry-run:
    description: 'Flag to perform a dry run of the deployment'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Run release-please
      uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{ inputs.github-token }}
        command: manifest

    - name: Show release status
      run: echo "Release created ${{ steps.release.outputs.releases_created }}"
      shell: bash

    - name: Checkout repository
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: actions/checkout@v3

    - name: Setup PHP
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: pcov

    - name: Install PHP dependencies
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: ramsey/composer-install@v1
      with:
        composer-options: '-oa --no-dev'

    - name: Build PHP dependencies
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      run: composer build
      shell: bash

    - name: Setup Node.js
      if: ${{ steps.release.outputs.releases_created == 'true' && inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install NPM dependencies
      if: ${{ steps.release.outputs.releases_created == 'true' && inputs.node-version }}
      run: npm install
      shell: bash

    - name: Build Node.js assets
      if: ${{ steps.release.outputs.releases_created == 'true' && inputs.node-version }}
      run: npm run build
      shell: bash

    - name: Upload plugin zip to release
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ${{ inputs.zip-file }}
        repo-token: ${{ inputs.github-token }}
        release-tag: ${{ steps.release.outputs.tag_name }}

    - name: 🚀 Deploy to WordPress.org
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: 10up/action-wordpress-plugin-deploy@develop
      env:
        SVN_PASSWORD: ${{ inputs.svn-password }}
        SVN_USERNAME: ${{ inputs.svn-username }}
        SLUG: ${{ inputs.plugin-slug }}
        BUILD_DIR: ${{ inputs.build-dir }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        VERSION: ${{ steps.release.outputs.tag_name }}
