name: '🚀 Plugin Release Deploy Action'
description: 'Release and deploy WordPress plugins using PHP and optionally Node.'

inputs:
  php-version:
    description: 'PHP version to setup'
    required: true
    default: '8.1'

  node-version:
    description: 'Node version to setup (optional, leave empty to skip)'
    required: false
    default: ''

  plugin-slug:
    description: 'Slug for the WordPress plugin on WordPress.org (required if deploy-to-wporg is true)'
    required: false
    default: ''

  build-dir:
    description: 'Build directory for the WordPress plugin (e.g. ./build/trunk/)'
    required: true

  zip-file:
    description: 'Zip file to upload to release (must exist when upload step runs)'
    required: true

  svn-username:
    description: 'SVN username for WordPress plugin deployment (required if deploy-to-wporg is true)'
    required: false
    default: ''

  svn-password:
    description: 'SVN password for WordPress plugin deployment (required if deploy-to-wporg is true)'
    required: false
    default: ''

  github-token:
    description: 'GitHub token for authentication'
    required: true

  dry-run:
    description: 'Flag to perform a dry run of the deployment (true/false)'
    required: false
    default: 'false'

  use-zipit:
    description: 'Use bin/zipit to build the plugin zip before uploading'
    required: false
    default: 'true'

  zipit-config:
    description: 'Optional path to .zipit-conf.php (relative to repo root)'
    required: false
    default: '.zipit-conf.php'

  deploy-to-wporg:
    description: 'Deploy to WordPress.org SVN after creating the release'
    required: false
    default: 'false'

  assets-dir:
    description: 'Directory containing WordPress.org assets (banners, icons, screenshots)'
    required: false
    default: '.wordpress-org'

outputs:
  release-created:
    description: 'Whether a release was created by release-please'
    value: ${{ steps.release.outputs.release_created }}
  tag-name:
    description: 'The release tag name (if a release was created)'
    value: ${{ steps.release.outputs.tag_name }}

runs:
  using: "composite"
  steps:
    - name: Run release-please
      uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{ inputs.github-token }}

    - name: Show release status
      run: echo "Release created ${{ steps.release.outputs.release_created }}"
      shell: bash

    - name: Checkout repository
      if: ${{ steps.release.outputs.release_created == 'true' }}
      uses: actions/checkout@v4

    - name: Setup PHP
      if: ${{ steps.release.outputs.release_created == 'true' }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: pcov

    - name: Install PHP dependencies
      if: ${{ steps.release.outputs.release_created == 'true' }}
      uses: ramsey/composer-install@v3
      with:
        composer-options: '-oa --no-dev'

    - name: Build PHP dependencies
      if: ${{ steps.release.outputs.release_created == 'true' }}
      run: composer build
      shell: bash

    - name: Setup Node.js
      if: ${{ steps.release.outputs.release_created == 'true' && inputs.node-version != '' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install NPM dependencies
      if: ${{ steps.release.outputs.release_created == 'true' && inputs.node-version != '' }}
      run: npm install
      shell: bash

    - name: Build Node.js assets
      if: ${{ steps.release.outputs.release_created == 'true' && inputs.node-version != '' }}
      run: npm run build
      shell: bash

    - name: Build plugin zip with ZipIt
      if: ${{ steps.release.outputs.release_created == 'true' && inputs.use-zipit == 'true' }}
      run: |
        if [ ! -x "bin/zipit" ]; then
          echo "::error::bin/zipit not found or not executable. Set use-zipit: 'false' or add ZipIt to your project."
          exit 1
        fi

        if [ ! -f "${{ inputs.zipit-config }}" ]; then
          echo "::error::ZipIt config file '${{ inputs.zipit-config }}' not found."
          exit 1
        fi

        echo "Running ZipIt (will auto-discover config at ${{ inputs.zipit-config }})"
        bin/zipit
      shell: bash

    - name: Upload plugin zip to release
      if: ${{ steps.release.outputs.release_created == 'true' }}
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ${{ inputs.zip-file }}
        repo-token: ${{ inputs.github-token }}
        release-tag: ${{ steps.release.outputs.tag_name }}

    - name: 🚀 Deploy to WordPress.org
      if: ${{ steps.release.outputs.release_created == 'true' && inputs.deploy-to-wporg == 'true' }}
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        dry-run: ${{ inputs.dry-run }}
      env:
        SVN_PASSWORD: ${{ inputs.svn-password }}
        SVN_USERNAME: ${{ inputs.svn-username }}
        SLUG: ${{ inputs.plugin-slug }}
        BUILD_DIR: ${{ inputs.build-dir }}
        ASSETS_DIR: ${{ inputs.assets-dir }}
        VERSION: ${{ steps.release.outputs.tag_name }}
